# Generated by Django 3.1.4 on 2020-12-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='for_class',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
