# Generated by Django 3.1.4 on 2020-12-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201225_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='generated_order_id',
            field=models.CharField(default='000000', max_length=50),
        ),
    ]
