# Generated by Django 3.1.4 on 2020-12-25 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_order_generated_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='username',
        ),
    ]
