# Generated by Django 3.1.4 on 2020-12-25 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201225_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='username',
            new_name='name',
        ),
    ]
